import { TranslationsList, setLocalizationConfigurations } from '@mongez/localization';

const translations: TranslationsList = {
  en: {
    newtitle: 'AddTodo List',
    title: 'Todo',
    addTodo: 'Add Todo',
    editTodo: 'Edit Todo',
    deleteTodo: 'Delete Todo',
    tableTitle: 'A list of your recent Todos.',
    all: 'All',
    completed: 'Completed',
    incompleted: 'Incompleted',
    notTodos: 'Todo List is empty',
    edit: 'Edit',
    delete: 'Delete',
    todoTitle: 'Todo Title',
    todoWrong: "You Don't have any todo yet",
    save: 'Save',
    cancel: 'Cancel',
    titleDelete: 'Are you sure you want to delete this todo?',
    actions: 'Actions',
    developedby: 'Developed by',
    author: 'Abdelrady Mohamed',
    copyrights: 'All rights reserved',
  },
  ar: {
    newtitle: 'إضافة مهمه جديدة',
    title: 'المهمة',
    addTodo: 'إضافة مهمة',
    editTodo: 'تعديل المهمة',
    deleteTodo: 'حذف المهمة',
    tableTitle: 'قائمة مهامك الحديثة.',
    all: 'الكل',
    completed: 'المكتملة',
    incompleted: 'الغير مكتملة',
    notTodos: 'لا يوجد اي مهام بالقائمة',
    edit: 'تعديل',
    delete: 'حذف',
    todoTitle: 'عنوان المهمه',
    todoWrong: 'ليس لديك اي مهام بالقائمة',
    save: 'حفظ',
    cancel: 'الغاء',
    titleDelete: 'هل تريد حذف هذه المهمه؟',
    actions: 'أجراءات',
    developedby: 'تم التصميم بواسطة',
    author: 'عبدالراضي محمد',
    copyrights: 'جميع الحقوق محفوظة',
  },
};

setLocalizationConfigurations({
  defaultLocaleCode: 'en',
  fallback: 'ar',
  translations: translations,
});